### ISSUE TITLE
[HW] <ARYAN ASTHANA>

### ISSUE THREAD

**Issue by asthanaary** [datastaxdevs/appdev-week3-graphql#100]
**Name:** <ARYAN ASTHANA>![Screenshot 2021-06-11 at 10 27 50 AM](https://user-images.githubusercontent.com/85698477/121633013-b29a4e80-ca9f-11eb-87be-87d8649ee296.png)**Email:** <asthanaary@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/aryan-asthana-91b9551a6/>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by clun** [comment]
Hey seems like you successfully deploy the application congratulations

Could you also insert one of your movie in the db please and share a screenshot ?
 
You can find instructions are on step7 and you can also check others homework submissions for ideas.
