### ISSUE TITLE
[HW] <NETFLIX CLONE WORKSHOP>

### ISSUE THREAD

**Issue by imdharish** [datastaxdevs/appdev-week3-graphql#105]
**Name:**  HARIRAM M<Hariram>
**Email:** <harish170902@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/hariram-m-704400210/

Attach the homework screenshots below:
-----------------------------------------

![Screenshot 2021-06-10 010650](https://user-images.githubusercontent.com/85640345/121651001-c782dc00-cab7-11eb-966d-fc401c10b561.png)
<![Screenshot 2021-06-10 010739](https://user-images.githubusercontent.com/85640345/121650886-ab7f3a80-cab7-11eb-8551-f5dc29c5c42d.png)>

**Comment by clun** [comment]
Hey seems like you successfully deploy the application congratulations

Could you also insert one of your movie in the db please and share a screenshot ?
 
You can find instructions are on step7 and you can also check others homework submissions for ideas.
