### ISSUE TITLE
[HW] <Nahom Kibreab Mehanzel>

### ISSUE THREAD

**Issue by NahomKibreab** [datastaxdevs/appdev-week3-graphql#11]
![astra datastax](https://user-images.githubusercontent.com/14014497/121408505-b9995380-c91d-11eb-91b8-e5b3a9ce9d31.png)
![netflix](https://user-images.githubusercontent.com/14014497/121408508-ba31ea00-c91d-11eb-9b33-abfdb6b95160.png)
![netlify](https://user-images.githubusercontent.com/14014497/121408510-baca8080-c91d-11eb-890f-e90595a2a08e.png)

**Comment by RyanWelford** [comment]
Thanks Nahom. We'd like to see an example of you adding your own movie to the data as well.
