### ISSUE TITLE
[HW] < Richard Rodriguez>

### ISSUE THREAD

**Issue by rich23odst** [datastaxdevs/appdev-week3-graphql#112]
**Name:** : Richard Rodriguez
**Email:** "richardodst1@gmail.com"
**Linkedin Profile: https://www.linkedin.com/in/richard-rodriguez-a370211a1, 

"working on it";

Attach the homework screenshots below:
-----------------------------------------
## "Thank you for the amazing workshop"

![React App](https://user-images.githubusercontent.com/65385243/121768012-b4e8c100-cb10-11eb-8460-fae43c9043d2.png)

**Comment by clun** [comment]
Hey seems like you successfully deploy the application congratulations

Could you also insert one of your movie in the db please and share a screenshot ?
 
You can find instructions are on step7 and you can also check others homework submissions for ideas.
