### ISSUE TITLE
netflix clone workshop

### ISSUE THREAD

**Issue by jeevitha2899** [datastaxdevs/appdev-week3-graphql#115]
M.jeevitha
mjeevithajss@gmail.com
![2021-06-12](https://user-images.githubusercontent.com/85688955/121772084-ec974d80-cb90-11eb-9a5f-289fe40d5632.png)
![2021-06-12 (2)](https://user-images.githubusercontent.com/85688955/121772091-f7ea7900-cb90-11eb-9fda-80917d57317e.png)
![2021-06-12 (3)](https://user-images.githubusercontent.com/85688955/121772103-059ffe80-cb91-11eb-998d-629fd5b93cb3.png)
![2021-06-12](https://user-images.githubusercontent.com/85688955/121772112-13ee1a80-cb91-11eb-86d8-8659dd0fd99b.png)

Finaloutput:  https://8888-rose-barracuda-77jc7nwi.ws-us09.gitpod.io/

**Comment by clun** [comment]
Hey seems like you successfully deploy the application congratulations

Could you also insert one of your movie in the db please and share a screenshot ?
 
You can find instructions are on step7 and you can also check others homework submissions for ideas.
