### ISSUE TITLE
NETFLIX CLONE <SWETHA G>

### ISSUE THREAD

**Issue by SwethaG1002** [datastaxdevs/appdev-week3-graphql#116]
**Name:** <SWETHA G>
**Email:** <swethagee1002@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/swetha-g-773a05209/>

![Screenshot (4)](https://user-images.githubusercontent.com/85694350/121774988-96330a80-cba2-11eb-9d07-af0a957ca602.png)

dataset is ready!

![Screenshot (23)](https://user-images.githubusercontent.com/85694350/121775003-aea32500-cba2-11eb-98a1-d511c30ee12f.png)

![Screenshot (31)](https://user-images.githubusercontent.com/85694350/121775024-ca0e3000-cba2-11eb-840a-361226e7ad9d.png)

![Screenshot (39)](https://user-images.githubusercontent.com/85694350/121775041-dc886980-cba2-11eb-970b-95965c7d872a.png)

![Screenshot (40)](https://user-images.githubusercontent.com/85694350/121775042-ddb99680-cba2-11eb-9016-d1b8d5fa56f3.png)

![Screenshot (41)](https://user-images.githubusercontent.com/85694350/121775051-e8742b80-cba2-11eb-9eaf-de0844a64fe4.png)

![Screenshot (42)](https://user-images.githubusercontent.com/85694350/121775054-ea3def00-cba2-11eb-9cda-e54ab631dbc0.png)

![Screenshot (43)](https://user-images.githubusercontent.com/85694350/121775057-ead68580-cba2-11eb-91bc-8bb00466c0d6.png)

Woah! App is created!

**Comment by clun** [comment]
Hey seems like you successfully deploy the application congratulations

Could you also insert one of your movie in the db please and share a screenshot ?
 
You can find instructions are on step7 and you can also check others homework submissions for ideas.
