### ISSUE TITLE
[HW] <Surya Kumar>

### ISSUE THREAD

**Issue by ProjectBaseview** [datastaxdevs/appdev-week3-graphql#123]
**Name:** <SURYAKUMAR S>
**Email:** <suryakumarmechz@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/surya-kumar-802903120/>
![A](https://user-images.githubusercontent.com/85806890/121800026-2463cb00-cc4d-11eb-84f7-3ec2def23117.png)
![as 1](https://user-images.githubusercontent.com/85806890/121800027-26c62500-cc4d-11eb-8c90-c2c7a12edd89.png)
![as 2](https://user-images.githubusercontent.com/85806890/121800028-29c11580-cc4d-11eb-8b97-d731d547ef47.png)
![as3](https://user-images.githubusercontent.com/85806890/121800029-2a59ac00-cc4d-11eb-9bca-f76e125321de.png)
![AS4](https://user-images.githubusercontent.com/85806890/121800030-2af24280-cc4d-11eb-9ad4-6bb53c203c54.png)
![AS5](https://user-images.githubusercontent.com/85806890/121800031-2cbc0600-cc4d-11eb-83ed-b38d06e2fd9e.png)
![as6](https://user-images.githubusercontent.com/85806890/121800032-2ded3300-cc4d-11eb-85c0-7be8e349fcff.png)
![as7](https://user-images.githubusercontent.com/85806890/121800034-2f1e6000-cc4d-11eb-9c23-1d3a81eac1d4.png)
![as8](https://user-images.githubusercontent.com/85806890/121800036-304f8d00-cc4d-11eb-830b-73dbefcf0a1b.png)
![as9](https://user-images.githubusercontent.com/85806890/121800038-30e82380-cc4d-11eb-94c2-99681e64c169.png)
![as10](https://user-images.githubusercontent.com/85806890/121800039-32195080-cc4d-11eb-8ad7-bd38f98331bd.png)
![as11](https://user-images.githubusercontent.com/85806890/121800041-33e31400-cc4d-11eb-9958-a323bbc66bbd.png)
![AS12](https://user-images.githubusercontent.com/85806890/121800042-35acd780-cc4d-11eb-8308-9b6ed4d0b8e4.png)
![AS13](https://user-images.githubusercontent.com/85806890/121800043-36de0480-cc4d-11eb-99aa-dbb7cbcf4b4b.png)
![AS14](https://user-images.githubusercontent.com/85806890/121800044-37769b00-cc4d-11eb-8470-6d0e96ce11ce.png)
![Final netflix cone home work done](https://user-images.githubusercontent.com/85806890/121800047-39405e80-cc4d-11eb-9665-3bd4fa380bd7.png)

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by clun** [comment]
Hey seems like you successfully deploy the application congratulations

Could you also insert one of your movie in the db please and share a screenshot ?
 
You can find instructions are on step7 and you can also check others homework submissions for ideas.
