### ISSUE TITLE
K S A R AMBEDKAR

### ISSUE THREAD

**Issue by ambedkar1985** [datastaxdevs/appdev-week3-graphql#125]
Name:K S A R AMBEDKAR
Email:ambedkar1985@gmail.com
Linkedin Profile:https://www.linkedin.com/in/k-s-a-r-ambedkar-50b12088/

Sreenshot Attachments
[[HW]-Assign . of Netflix live.pdf](https://github.com/datastaxdevs/workshop-graphql-netflix/files/6643696/HW.-Assign.of.Netflix.live.pdf)

**Comment by clun** [comment]
Hey seems like you successfully deploy the application congratulations

Could you also insert one of your movie in the db please and share a screenshot ?
 
You can find instructions are on step7 and you can also check others homework submissions for ideas.
