### ISSUE TITLE
Netflix_workshop

### ISSUE THREAD

**Issue by Mubirihan** [datastaxdevs/appdev-week3-graphql#133]
Name: J. Mubina banu
Email: mubinabanu19@gmail.com 

Attach the homework screenshots below:
-----------------------------------------
![Capture](https://user-images.githubusercontent.com/82943071/122074044-83287080-ce16-11eb-9aa8-cdaaffc6a495.PNG)
![Capture PNG1](https://user-images.githubusercontent.com/82943071/122074213-a7844d00-ce16-11eb-8c63-d2853cdcaf82.PNG)
![Capture PNG2](https://user-images.githubusercontent.com/82943071/122074312-bb2fb380-ce16-11eb-8248-6b7cb5dc4377.PNG)
![Capture PNG3](https://user-images.githubusercontent.com/82943071/122074358-c7b40c00-ce16-11eb-9ab2-02ec280184ab.PNG)
![Capture PNG4](https://user-images.githubusercontent.com/82943071/122074406-d13d7400-ce16-11eb-9851-efb180117ec1.PNG)
![Capture PNG5](https://user-images.githubusercontent.com/82943071/122074471-df8b9000-ce16-11eb-85b5-c861626ccd2b.PNG)
![Capture PNG6](https://user-images.githubusercontent.com/82943071/122074559-f29e6000-ce16-11eb-9832-6844a6bb544f.PNG)
![Capture PNG7](https://user-images.githubusercontent.com/82943071/122074614-fb8f3180-ce16-11eb-9355-a4dd03be8fab.PNG)

**Comment by clun** [comment]
Hey seems like you successfully deploy the application congratulations.

Could you also insert one of **your movie in the db please** and share a screenshot ?

You can find instructions are on [step7](https://github.com/datastaxdevs/workshop-graphql-netflix#7-insert-values-in-movie-table) and you can also check others homework submissions for ideas.
