### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by LakshitaT** [datastaxdevs/appdev-week3-graphql#156]

**Comment by ganesh1499** [comment]
I don't know how to change

**Comment by ganesh1499** [comment]
Let me know how to do it

**Comment by ganesh1499** [comment]
Is that resolved?

**Comment by ganesh1499** [comment]
I'm sorry I'm now not in live bcoz of personal reasons

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by LakshitaT** [comment]
I think i unknowingly closed something. I have opened it again.

I am not sure of the specifics or what did i just do but i think it works
fine and you can comment the homework whenever you want

**Comment by ganesh1499** [comment]
Thanks😊👍  sure I'll respond
