### ISSUE TITLE
[HW] <Rounak Tadvi>

### ISSUE THREAD

**Issue by RounakTadvi** [datastaxdevs/appdev-week3-graphql#204]
**Name:** Rounak Tadvi
**Email:** rounaktadvi786@gmail.com
**Linkedin Profile:** www.linkedin.com/in/rounaktadvi

Attach the homework screenshots below:
-----------------------------------------

![Screenshot 2021-07-01 at 10 03 19 PM](https://user-images.githubusercontent.com/38634459/124159477-d6f2b500-dab8-11eb-83b5-9b1024114ac0.png)
![Screenshot 2021-07-01 at 10 06 25 PM](https://user-images.githubusercontent.com/38634459/124159493-da863c00-dab8-11eb-8cb5-946bc8e4e3e1.png)
![Screenshot 2021-07-01 at 10 06 56 PM](https://user-images.githubusercontent.com/38634459/124159504-dbb76900-dab8-11eb-8765-9ac7ee3a433f.png)
![Screenshot 2021-07-01 at 10 08 04 PM](https://user-images.githubusercontent.com/38634459/124159512-deb25980-dab8-11eb-9d63-e2925081bf95.png)

**Comment by SonicDMG** [comment]
Hi there Rounak, thank you for your submission. All looks good except I don't see a video that you inserted per step 2 in the homework.
2. Insert a movie of your choice in the database.

Please insert a video of your own and include a screenshot. Thank you.

**Comment by RounakTadvi** [comment]
![Screenshot 2021-07-02 at 10 05 55 PM](https://user-images.githubusercontent.com/38634459/124304747-c8240500-db81-11eb-89d3-8757b1f5188c.png)
![Screenshot 2021-07-02 at 9 49 58 PM](https://user-images.githubusercontent.com/38634459/124304759-cc502280-db81-11eb-9058-790154fdab48.png)

**Comment by SonicDMG** [comment]
Ok, looks good, thank you.

**Comment by HadesArchitect** [comment]
Hey **Rounak Tadvi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/bZIDZ5YYRc-VuKiPWtgRVw

**Comment by RounakTadvi** [comment]
Thanks for the badge @HadesArchitect
