### ISSUE TITLE
[HW] <SAHIL BAGADE>

### ISSUE THREAD

**Issue by sahilbagade** [datastaxdevs/appdev-week3-graphql#26]
![Screenshot 2021-06-10 002836](https://user-images.githubusercontent.com/45709657/121413249-1f6bf680-c983-11eb-8a98-6627cce5d6ec.png)
![Screenshot 2021-06-10 002928](https://user-images.githubusercontent.com/45709657/121413268-24c94100-c983-11eb-9e5b-eced2a307a6a.png)
![Screenshot 2021-06-10 003323](https://user-images.githubusercontent.com/45709657/121413710-986b4e00-c983-11eb-9ef6-440e8a65373b.png)

**Comment by clun** [comment]
Thank you SAHIL this is good. Can you please also insert one of your favourite movie. Instructions to do is explained step 7
