### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by juliann** [datastaxdevs/appdev-week3-graphql#306]
**Name:** Julian Nadarzy
**Email:** julian.nadarzy@gmail.com

**Linkedin Profile:** <https://www.linkedin.com/in/julian-nadarzy-74b7b810/>

Attach the homework screenshots below:
-----------------------------------------

![netflix 1](https://user-images.githubusercontent.com/1125748/126496642-1bcc8415-12ef-4f10-8cdd-52adecad7bc2.jpg)
![netflix 2](https://user-images.githubusercontent.com/1125748/126496648-7a1064f6-5314-4ba0-9412-909971ae782f.jpg)
![netflix 3](https://user-images.githubusercontent.com/1125748/126496650-86276450-f08a-401f-a067-77a07c20c24d.jpg)
![netflix 4](https://user-images.githubusercontent.com/1125748/126496653-5cf12125-f15f-430a-a872-ab73a91fb35f.jpg)
![netflix 5](https://user-images.githubusercontent.com/1125748/126496654-2586cdf1-df8c-437d-bd33-5c3e848b9284.jpg)

**Comment by HadesArchitect** [comment]
Hey **Julian Nadarzy**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/YDtRWsUmR4SQy5PPp4tgmg
