### ISSUE TITLE
[HW] Gurmehar Bakshi

### ISSUE THREAD

**Issue by gsbakshi** [datastaxdevs/appdev-week3-graphql#309]
**Name:** Gurmehar Singh Bakshi
**Email:** greaser.bakshi@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/gsbakshi/

Attach the homework screenshots below:
-----------------------------------------

![Screenshot 2021-07-21 at 10 01 10 AM](https://user-images.githubusercontent.com/61559056/126509352-006b5f25-b0de-442e-a219-d7951f897a5d.png)

![Screenshot 2021-07-21 at 10 00 27 AM](https://user-images.githubusercontent.com/61559056/126509302-da9e7fa1-e8f8-413b-aa4d-66ee1afec3bd.png)

![Screenshot 2021-07-21 at 10 00 54 AM](https://user-images.githubusercontent.com/61559056/126509315-89088e78-01d3-419b-9c43-9728e455b0e8.png)

![Screenshot 2021-07-21 at 10 03 12 AM](https://user-images.githubusercontent.com/61559056/126509369-c0d347a9-4c71-4b4d-bed0-777002d9fd5a.png)

-----------------------------------------

Link to my current repo : https://github.com/gsbakshi/gflix
Link to deployed app : https://g-flix.netlify.app/

>I had built this on my local machine. Link to the version of my branch before I rewrote the CRA bootstrapped readme.
>https://github.com/gsbakshi/gflix/tree/7d03463708762c8907fe5545e86f95793ed25d47

**Comment by HadesArchitect** [comment]
Hey **Gurmehar Singh Bakshi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/nr5N0bAcTLeWU0VfaoCoFA

**Comment by SonicDMG** [comment]
Ha fun, looks like you changed some of the styles, nice. I especially liked your added "GFlix", lol.

**Comment by gsbakshi** [comment]
@SonicDMG Haha thanks, GFlix was just a spur of the moment thing, glad you liked it :satisfied:

I though I'll use this workshop to practice my Sass skills as well, lol. This was a fun workshop. Looking forward to trying my hand on the battlestax application as well. 

Also, what's the procedure for getting the gold badge after completing the exercises?
