### ISSUE TITLE
[HW] <Aaliya Kulsoom>

### ISSUE THREAD

**Issue by aalu45** [datastaxdevs/appdev-week3-graphql#31]
[
![Screenshot (2)](https://user-images.githubusercontent.com/71878686/121416916-fb121900-c986-11eb-9d69-a6b57dee285a.png)
](url)

**Comment by clun** [comment]
Hello Aaliya, this is great the application is deployed.

Could you also insert one of your movie in the db please ? 
You can find instructions are on step7 and you can also check others homework submissions for ideas.
