### ISSUE TITLE
[HW] Lee Yong Wei

### ISSUE THREAD

**Issue by fackerlee** [datastaxdevs/appdev-week3-graphql#314]
Name: Lee Yong Wei
Email: fackerlee@gmail.com
Linkedin Profile: https://www.linkedin.com/in/yongw3i/

https://focused-wescoff-32e3ed.netlify.app/

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/76558523/126525366-a9255c00-3281-4e66-9c5e-265fb9cc1710.png)

![image](https://user-images.githubusercontent.com/76558523/126525417-6f16c766-201d-4254-b565-fc47b1fa65c0.png)

**Comment by SonicDMG** [comment]
Hey there Lee, what custom video did you add? I don't see one on your site. Nice job getting that up and running.

**Comment by fackerlee** [comment]
@SonicDMG 

HI Sonic , I think i had added 

![image](https://user-images.githubusercontent.com/76558523/126697149-1de8747e-ec41-47fa-92e4-0e3a8fa09a07.png)

**Comment by SonicDMG** [comment]
Awesome, thank you very much for following up.

**Comment by HadesArchitect** [comment]
Hey **Lee Yong Wei**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/qLWrNEFYR8qOS_cIQBGqCQ
