### ISSUE TITLE
[HW] Michelle Greyson wk3

### ISSUE THREAD

**Issue by michellengreyson** [datastaxdevs/appdev-week3-graphql#332]
**Name:** Michelle Greyson
**Email:** michellengreyson@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/michellengreyson/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![Screenshot (52)](https://user-images.githubusercontent.com/56977312/126533730-35264377-3505-46a1-b944-0ce4246ea6cf.png)
![Screenshot (54)](https://user-images.githubusercontent.com/56977312/126534788-3f19acac-82e7-4d1b-a8c7-ada27e151d9a.png)

**Comment by HadesArchitect** [comment]
Hey **Michelle Greyson**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/JtkEJAYvSQSjQNWbn0GBaw

**Comment by michellengreyson** [comment]
Thanks so much for a great series of learning. I am looking forward to more courses :)
