### ISSUE TITLE
[HW] <HARIRAM M>

### ISSUE THREAD

**Issue by imdharish** [datastaxdevs/appdev-week3-graphql#34]
![Screenshot_2021_0610_010115](https://user-images.githubusercontent.com/85640345/121417847-f732c680-c987-11eb-99ca-690c87dbdd60.jpg)
![Screenshot 2021-06-10 010650](https://user-images.githubusercontent.com/85640345/121418168-4f69c880-c988-11eb-9950-f4b1a21fcf06.png)
![Screenshot 2021-06-10 010739](https://user-images.githubusercontent.com/85640345/121418172-509af580-c988-11eb-9ece-56b24d508901.png)

**Comment by clun** [comment]
Could you also insert one of your movie in the db please ? 
You can find instructions are on step7 and you can also check others homework submissions for ideas.
