### ISSUE TITLE
[HW] Mahesh Dhavane

### ISSUE THREAD

**Issue by razor300** [datastaxdevs/appdev-week3-graphql#345]
**Name:** Mahesh Dhavane
**Email:** maheshdhawne2000@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/mahesh-dhavane-0aa6201ba/
**Netlify Link:** https://practical-brown-cfef08.netlify.app/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
-- images removed by team --

![image](https://user-images.githubusercontent.com/72245057/126541695-ff0316e8-7217-4e40-a574-0512cd17081c.png)

![image](https://user-images.githubusercontent.com/72245057/126541800-eabdeb43-050d-43ab-9242-346778066571.png)

**Comment by SonicDMG** [comment]
Hi Mahesh, nice job getting the app deployed. I don't see your custom video though on your site. Could you please add one and take a screenshot or just post your netlify link. If you did add one please point out which one. Thank you.

**Comment by SonicDMG** [comment]
Also, I had to remove some of your images because they contained your Astra token. Please delete your token from the Astra UI so there are no security issues.

**Comment by razor300** [comment]
posted an netlify link, pls do check

**Comment by HadesArchitect** [comment]
Hey **Mahesh Dhavane**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/2thlMy_qRfSneNuUart9VA
