### ISSUE TITLE
[HW] <[Netflix Clone]. Boyina Venu>

### ISSUE THREAD

**Issue by BOYINAVENU** [datastaxdevs/appdev-week3-graphql#403]
**Name:** Boyina Venu
**Email:** venu.boyina31@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/boyina-venu-8700bb1a0

Attach the homework screenshots below:
-----------------------------------------

<
![20210723_001733](https://user-images.githubusercontent.com/87844096/126737578-44a16c2d-c653-4e2f-aebf-025ffebbc19f.jpg)
>

**Comment by hemidactylus** [comment]
Hi!
You are doing great! But please complete the homework by inserting a new movie and sending a screenshot of the app running in Netlify with your movie added. Also the screenshot should make it clear that the app is deployed in Netlify (the browser's address bar should be visible). Thank you and good luck!
