### ISSUE TITLE
[Netflixclone] <Nitikawadhwa>

### ISSUE THREAD

**Issue by Nitikawadhwa13** [datastaxdevs/appdev-week3-graphql#44]
Done with the app 

![Screenshot (552)](https://user-images.githubusercontent.com/85647032/121439897-7504cb00-c9a4-11eb-833b-6ad01a5d5549.png)

**Comment by clun** [comment]
Hi seems you have successfully deployed the application.

Could you also insert one of your movie in the db please ? 
You can find instructions are on step7 and you can also check others homework submissions for ideas.

Thank you
