### ISSUE TITLE
[HW] Anni Huang

### ISSUE THREAD

**Issue by anni-huang** [datastaxdevs/appdev-week3-graphql#447]
**Name:** Anni Huang
**Email:** anni.huany@gmail.com
**Linkedin Profile:** https://www.linkedin.com/huanganni/

Attach the homework screenshots below:
-----------------------------------------

https://gracious-mclean-144fa2.netlify.app/
<img width="1232" alt="Screen Shot 2021-07-25 at 11 54 58 PM" src="https://user-images.githubusercontent.com/69827222/126930981-b5b06c2d-493a-4f67-b113-19aad43ad920.png">

**Comment by hemidactylus** [comment]
Hi, Anni, congratulations, well done!
Enjoy your badge!
(I'd actually like a movie called "superfun new movie", you know?)

(I deleted one of your screenshots since it was showing your secret Astra DB token. You should go to Astra and revoke the token).

**Comment by HadesArchitect** [comment]
Hey **Anni Huang**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/lT0obs5BRt6EsUjpbCENxA

**Comment by anni-huang** [comment]
Thank you Stephano!!
