### ISSUE TITLE
[HW] <Nancy Bullis>

### ISSUE THREAD

**Issue by NancyJaneBullis** [datastaxdevs/appdev-week3-graphql#471]
**Name:** Nancy Bullis
**Email:** nancybullis3@gmail.com
**Linkedin Profile:** www.linkedin.com/in/nancyjanebullis

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/83715570/127388998-a0160b5d-069d-477f-8686-a8e163578c91.png)
![image](https://user-images.githubusercontent.com/83715570/127389158-7952bb21-8202-49ee-87cd-649ba7fbcc6d.png)
![image](https://user-images.githubusercontent.com/83715570/127389310-d3e241a0-f068-4eeb-85dc-2a5f6c4cc308.png)
![image](https://user-images.githubusercontent.com/83715570/127390167-591a3dfc-1b9d-4fe7-81a9-5d2dae465bc6.png)

<SCREENSHOTS>

**Comment by hemidactylus** [comment]
Hello there, Nancy,
it seems that the screenshots are too low-res to properly see what is going on: have you added a new movie of your choice to the database, as required by the instructions at https://github.com/datastaxdevs/appdev-week3-graphql/blob/main/README.md#homework ? Please take even just a single screenshot with a slightly better resolution that shows your own custom movie in your Netflix clone, thank you!

See you soon!

**Comment by NancyJaneBullis** [comment]
Hi Stefano,
Thank you for reviewing my work. I'm sorry the screen resolution was so
low. I've changed the resolution and increased the brightness so hopefully
it's easier to read.
I have resubmitted my homework of four screenshots as a new issue.
What I was trying to show you last time, but the resolution was too low,
was that I had inserted a new movie Interstellar with a new description for
that movie. I used the URL for the Inception movie which I thought was okay
to do and that I didn't need to create a new url for Interstellar on the
imgur web site and use that. This is the first screen shot. Today I redid
this and inserted Interstellar but this time used a link to a YouTube
trailer which I've shown in the second screen shot. The third screen shot
shows that the movie was successfully included in the database. The fourth
screen shot shows that I've deployed the site and that Interstellar is
included. Unfortunately the image is blank and doesn't show the YouTube
video. It does however say Interstellar.  I hope this is okay. Please let
me know. Thanks Stefano.

**Comment by hemidactylus** [comment]
Hello!
Well done! Now it's very clear, thank you! And the homework is completed, yay!
I'll close this issue then and award the badge on the new issue you opened.
Enjoy your badge!

**Comment by NancyJaneBullis** [comment]
Hi Stefano, I'm glad everything was clear this time and the homework is
completed. Thank you!
