### ISSUE TITLE
[HW] Adharsh Jolly 

### ISSUE THREAD

**Issue by Adharshjolly** [datastaxdevs/appdev-week3-graphql#496]
**Name:** Adharsh Jolly 
**Email:** adharshjolly23@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/adharsh-jolly 

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

[Live Demo ](https://aj-netflix-clone.netlify.app)

![IMG_20210907_223733.jpg](https://user-images.githubusercontent.com/86960153/132435842-6d89a0e6-0f58-4570-b810-cf7f1cff9e6b.jpg)

**Comment by HadesArchitect** [comment]
Hey **Adharsh Jolly**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/A1d9tP6mQY2vDs8itmmHiw
