### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by saikiran-seepana** [datastaxdevs/appdev-week3-graphql#504]
**Name:** Saikiran Seepana
**Email:** saikiranseepana@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/seepana-saikiran/

Attach the homework screenshot below:
-----------------------------------------
![Screenshot from 2021-09-22 23-44-20](https://user-images.githubusercontent.com/28986697/134398965-19fa0f1b-9a97-4734-9fb2-afe54ea0fece.png)
![Screenshot from 2021-09-22 23-44-07](https://user-images.githubusercontent.com/28986697/134398979-97328036-5d21-43b0-adee-028712ea0e3d.png)

**Comment by hemidactylus** [comment]
Hello! Please show us a screenshot with the movie you added to the database to complete the homework (and possibly give us its movie name and genre to help us locate it faster).
Or if you added a genre, tell us its name so we can check! Thank you!

And don't forget to add the label "wait for review" to this issue when you're done so we can grade it quicker!

See you soon!
