### ISSUE TITLE
[HW] Ankit Sharma

### ISSUE THREAD

**Issue by shaank121** [datastaxdevs/appdev-week3-graphql#511]
**Name:** Ankit Sharma
**Email:** shaank121
**Linkedin Profile:** https://www.linkedin.com/in/shaank121

Attach the homework screenshot below:
-----------------------------------------
I have added "Test" movie to Astra DB 
link to my app: https://cocky-wescoff-679c04.netlify.app/

![image](https://user-images.githubusercontent.com/31551050/134401158-42035b94-af47-45c2-b82d-9d8fc3f9ebe9.png)

**Comment by hemidactylus** [comment]
Hello, Ankit!
Congratulations, the homework is complete! But please can you edit the above with your full email? Otherwise we cannot issue you the badge!

Please add the "wait for review" label to this issue when you're done so we can review and complete the submission!
Thank you!
