### ISSUE TITLE
[HW] Rachel Chalet

### ISSUE THREAD

**Issue by rachelchalet** [datastaxdevs/appdev-week3-graphql#519]
**Name:** Rachel Chalet
**Email:** rachelchalet99@gmail.com
**Linkedin Profile:** www.linkedin.com/in/rachel-chalet-78966b1b3

link to the deployed Netlify site: https://agitated-feynman-e16249.netlify.app/
Attach the homework screenshot below:
-----------------------------------------
![netflix_clone_hw](https://user-images.githubusercontent.com/72330777/134404241-d9ba93b4-4b79-493b-b023-db8dac08422a.JPG)

<SCREENSHOT>

**Comment by hemidactylus** [comment]
Hello there! Please can you show the genre/movie you added to your Netlfix clone?
Then we will grade the homework!

(don't forget to add the "wait for review" label to this issue wen you are done!)

Thank you, see you soon!
