### ISSUE TITLE
[HW] <Avi Shekhar>

### ISSUE THREAD

**Issue by AVISHEKHAR** [datastaxdevs/appdev-week3-graphql#53]
###netlify **screenshot**
![image](https://user-images.githubusercontent.com/53835065/121473351-2aa13f80-c9e0-11eb-9efa-2b64c4242b0a.png)

###**app working fine screenshot of deployed production**
![image](https://user-images.githubusercontent.com/53835065/121473554-79e77000-c9e0-11eb-9dc4-f580f86aabd8.png)

### **GitPod Deployement steps Screenshot**
![image](https://user-images.githubusercontent.com/53835065/121473898-f1b59a80-c9e0-11eb-9588-790fae589091.png)

**Comment by clun** [comment]
Hey, seems you successfully deployed the application.

Could you also insert one of your movie in the db and do a screenhot please ? 
You can find instructions are on step7 and you can also check others homework submissions for ideas.
