### ISSUE TITLE
[HW] Cezar Lupescu

### ISSUE THREAD

**Issue by Goedoun** [datastaxdevs/appdev-week3-graphql#543]
![Screenshot (82)](https://user-images.githubusercontent.com/90771006/134533111-3f880437-4e94-4da8-87e1-441ff66c8a98.png)
![Screenshot (87)](https://user-images.githubusercontent.com/90771006/134533174-86f2edc5-4615-42a4-9d8f-8ad6e09a6dec.png)

_Originally posted by @Goedoun in https://github.com/datastaxdevs/appdev-week3-graphql/issues/523#issuecomment-925903678_

**Comment by SonicDMG** [comment]
Closing as duplicate
