### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by vksathish** [datastaxdevs/appdev-week3-graphql#546]
**Name:** Sathish Vankayala
**Email:** sathishvankayala@gmail.com
**Linkedin Profile:** REPLACE_ME

Attach the homework screenshot below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/90789259/134585160-d000744d-8141-4eee-b586-1090593d2ca0.png)

**Comment by hemidactylus** [comment]
Hello, Sathish!
We could not find the movie/genre you added to your own deployed application https://boring-nightingale-d3abf6.netlify.app/, could you please upload a screenshot showing that and pointing us to it? This way we will be able to grade your homework!

Thank you and see you later!
p.s. Don't forget to re-label this issue with "wait for review" so we will look into it again soon!
