### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by thiagomarsal** [datastaxdevs/appdev-week3-graphql#555]
**Name:** Thiago Marsal Farias
**Email:** thiagomarsal.farias@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/thiago-marsal-farias/

Attach the homework screenshot below:
-----------------------------------------
https://react-netflix-clone-thiagomarsal.netlify.app/
*Technology*
![image](https://user-images.githubusercontent.com/8714453/134594210-5a379284-83a3-4118-9634-31d932e8cec6.png)

![image](https://user-images.githubusercontent.com/8714453/134594275-c95835b3-f067-43ad-94de-a6076b8001b7.png)

**Comment by HadesArchitect** [comment]
Hey **Thiago Marsal Farias**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/sk9GRo3aRDOLj3YFxkuaHw
