### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by ianlaporte** [datastaxdevs/appdev-week3-graphql#561]
**Name:** ianlaporte
**Email:** ianlaporte@gmail.com
**Linkedin Profile:** www.linkedin.com/in/ianlaporte
**GitHub Profile:** https://github.com/ianlaporte/appdev-week3-graphql

Attach the homework screenshot below:
-----------------------------------------

[My image](https://github.com/ianlaporte/appdev-week3-graphql/tree/iansubbranch/img/ianlaporte_forBadge_added_FilmElephantsDream.png)

<SCREENSHOT>
![ianlaporte_forBadge_added_FilmElephantsDream](https://user-images.githubusercontent.com/44279639/134628137-412721de-c9bc-4451-902a-d348709f67f6.png)

**Comment by hemidactylus** [comment]
Closing as it is a duplicate of #560
