### ISSUE TITLE
[HW] Build a Netflix clone with GraphQL, React and a NoSQL DB

### ISSUE THREAD

**Issue by logesh-kumar** [datastaxdevs/appdev-week3-graphql#564]
**Name:** Logesh Kumar 
**Email:** phoenix.logu@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/logeshkumar87/

Attach the homework screenshot below:
-----------------------------------------

![Graphql Playground - mutation for adding new movie](https://github.com/logesh-kumar/netflix-clone/blob/main/img/new-movie-gql-screenshot.png)

![Website - New movie screenshot](https://github.com/logesh-kumar/netflix-clone/blob/main/img/new-movie-screenshot.png)

[Netlify url](https://vigorous-euclid-adc98e.netlify.app/)

**Comment by hemidactylus** [comment]
My sincerest congratulations! You did a major restyling of your Netflix clone!
Enjoy your well-deserved badge!

**Comment by HadesArchitect** [comment]
Hey **Logesh Kumar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/hkDfQW00SbOj2mbTBgNasg

**Comment by logesh-kumar** [comment]
Thank you @HadesArchitect @hemidactylus
