### ISSUE TITLE
[HW] S.Sakthivel

### ISSUE THREAD

**Issue by sakthisupermans** [datastaxdevs/appdev-week3-graphql#60]
**Name:** S.Sakthivel
**Email:** sakthisupermans@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/sakthivel-saravanathangam-002825210/

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/85664948/121499462-0b63db80-c9fb-11eb-91c2-d949353d8632.png)
![image](https://user-images.githubusercontent.com/85664948/121499638-34846c00-c9fb-11eb-9280-874229d64462.png)
![image](https://user-images.githubusercontent.com/85664948/121499725-4108c480-c9fb-11eb-9298-3352ad5014da.png)
![image](https://user-images.githubusercontent.com/85664948/121499756-4cf48680-c9fb-11eb-911d-b0b365ba1348.png)

**Comment by clun** [comment]
Hey seems like your successfully deployed the application

Could you also insert one of your movie in the db and do a screenshot please ? 

You can find instructions are on step7 and you can also check others homework submissions for ideas.
