### ISSUE TITLE
[HW] <Bhabani Prasad Upadhyaya>

### ISSUE THREAD

**Issue by bhabaniupadhyaya18** [datastaxdevs/appdev-week3-graphql#67]
**Name:**  Bhabani Prasad Upadhyaya 
**Email:** <bhabani.upadhyaya@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/bhabani-upadhyaya-49223a19/>

Attach the homework screenshots below:
-----------------------------------------
<img width="960" alt="Screenshot 2021-06-10 15 59 54" src="https://user-images.githubusercontent.com/85641122/121510588-6b5f7f80-ca05-11eb-84b9-7a13065bcfa1.png">

**Comment by clun** [comment]
Hey sounds the app is now running with content.

Could you also insert one of your movie in the db please ? 
You can find instructions are on step7 and you can also check others homework submissions for ideas.
