### ISSUE TITLE
[HW] Kshitij Gupta

### ISSUE THREAD

**Issue by kshitijgupta74** [datastaxdevs/appdev-week3-graphql#72]
**Name:** Kshitij Gupta
**Email:** kshitijgupta74@gmail.com
**Linkedin Profile:** = https://www.linkedin.com/in/kshitijgupta74/

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/84751973/121519105-eda07180-ca0e-11eb-96ee-e359646bb120.png)

<SCREENSHOTS>

**Comment by clun** [comment]
Hey seems like you successfully deploy the application congratulations

Could you also insert one of your movie in the db please and share a screenshot ?
 
You can find instructions are on step7 and you can also check others homework submissions for ideas.
