### ISSUE TITLE
[HW] Ansan George Antony

### ISSUE THREAD

**Issue by AnsanAntony** [datastaxdevs/appdev-week3-graphql#92]
**Name:** Ansan George Antony
**Email:** ansan.geroge@btech.christuniversity.in
**Linkedin Profile:** https://www.linkedin.com/in/ansan-antony-68b6a31b1

![image](https://user-images.githubusercontent.com/82665251/121566864-fc971c00-ca2e-11eb-85d9-94e2324cc557.png)

![image](https://user-images.githubusercontent.com/82665251/121566950-12a4dc80-ca2f-11eb-8d95-4d43658468e3.png)

![image](https://user-images.githubusercontent.com/82665251/121566997-20f2f880-ca2f-11eb-9ee1-0674820b4959.png)

![image](https://user-images.githubusercontent.com/82665251/121567051-2bad8d80-ca2f-11eb-8b3e-9326f6061ba1.png)

![image](https://user-images.githubusercontent.com/82665251/121567111-3f58f400-ca2f-11eb-8d9e-262098dee9a3.png)

**Comment by clun** [comment]
Hey seems like you successfully deploy the application congratulations

Could you also insert one of your movie in the db please and share a screenshot ?
 
You can find instructions are on step7 and you can also check others homework submissions for ideas.
