### ISSUE TITLE
[HW] Saifali Patel

### ISSUE THREAD

**Issue by saifali-patel** [datastaxdevs/appdev-week3-graphql#95]
**Name:** Saifali Patel
**Email:** saifalipatel99@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/saifali-patel/

Attach the homework screenshots below:
-----------------------------------------
Adding the movie John Wick ,
<img width="1181" alt="121424269-34945580-c982-11eb-87f6-55b1240ee9f8" src="https://user-images.githubusercontent.com/61909924/121584699-cebbd280-ca42-11eb-9740-180e5fd2a9b2.png">

Netflix Clone running on Netlify showing the new added movie "John Wick", link : https://workshopnetflix.netlify.app ,
<img width="1237" alt="121424445-66a5b780-c982-11eb-962a-3aa2aaa2a078" src="https://user-images.githubusercontent.com/61909924/121584727-d7140d80-ca42-11eb-8d57-091c3c3b44ef.png">

Great Workshop !
Enjoyed it 😁

**Comment by clun** [comment]
Hey seems like you successfully deploy the application congratulations

Could you also insert one of your movie in the db please and share a screenshot ?
 
You can find instructions are on step7 and you can also check others homework submissions for ideas.
